PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -arch arm64
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -gdwarf-2
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk
PLATFORM_COMPILE_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) -DPPBOX_CONTANINER=DequeEx

PLATFORM_LINK_FLAGS		:= $(PLATFORM_COMPILE_FLAGS) 

PLATFORM_DISABLE_FLAGS		:= -Wl,-Os -Wl,--exclude-libs -Wl,-rpath rcs

PLATFORM_DEPEND_LIBRARYS_DIR    := ios

PLATFORM_DEPEND_LIBRARYS    := $(PLATFORM_DEPEND_LIBRARYS) ssl crypto
