// := framework_config.h

#define FRAMEWORK_WITH_LIB_SSL

#define FRAMEWORK_WITH_LIB_UUID

#define FRAMEWORK_NETWORK_WITH_SERVICE_CACHE

#define FRAMEWORK_WITH_LIB_ICONV

#define FRAMEWORK_MEMORY_DEBUG_MEMORY_POOL

#if 0

PROJECT_DEPEND_LIBRARYS	:= uuid ssl

#endif
