
.PHONY: publish
publish : $(TARGET_FILE_FULL)
	@$(ECHO) "$(MKDIR) $(ROOT_PUBLISH_DIRECTORY)/$(PLATFORM_STRATEGY_NAME)"
	@$(MKDIR) $(ROOT_PUBLISH_DIRECTORY)/$(PLATFORM_STRATEGY_NAME)
	@$(ECHO) "$(LN) $(TARGET_FILE_FULL) $(ROOT_PUBLISH_DIRECTORY)/$(PLATFORM_STRATEGY_NAME)/$(TARGET_FILE)"
	@$(LN) $(TARGET_FILE_FULL) $(ROOT_PUBLISH_DIRECTORY)/$(PLATFORM_STRATEGY_NAME)/$(TARGET_FILE)
